C:/Users/maxim/Desktop/mipt/grade_1/course_dedinskiy/hw_onegin/general.h File Reference
General functions to be used in all projects.
#include <assert.h>
Classes
struct Line
Handmade stringview.
struct File
Struct to store file's information into.
Macros
#define DEBUG_NUMBER_PRINT() printf(`[deb] %d [deb]\n`, DEBUG_NUMBER++);
#define DEBUG_LETTER_PRINT() printf(`[deb] %c [deb]\n`, DEBUG_LETTER++);
#define DEBUG_NUMBER_INCR() DEBUG_NUMBER++;
#define DEBUG_LETTER_INCR() DEBUG_LETTER++;
#define DEBUG(LEVEL) if (LEVEL <= KCTF_DEBUG_LEVEL)
Typedefs
typedef struct Line Line_t
Typedef for Line.
typedef struct File File_t
Typedef for File.
Enumerations
enum CURRENT_PROJECT_SETTINGS { STROFA_SIZE = 14,
RHYME_DEPTH = 4
 }
Current project's setting.
enum ERRORS { ERROR_FILE_NOT_FOUND = -10,
ERROR_BIG_FILE,
ERROR_MALLOC_FAIL
 }
Errors codes.
Functions
void qqh_sort (void *arr, const size_t elem_cnt, const size_t elem_size, int(*comp)(const void *elem1, const void *elem2))
Quadratic sort.
int compare_lines_letters (const void *elem1, const void *elem2)
Comparator for two lines.
int reverse_compare_lines_letters (const void **elem1, const void **elem2)
Reversed comparator for two lines.
void free_memory_file (const File_t *file)
Calls all necessary free's.
int read_file (File_t *file, const char *name)
Reads file.
int read_lines (File_t *file)
Reads lines from file.
void print_file (const File_t *file, const char *fout_name, const char *mode)
Prints file into given file.
int is_countable (const unsigned char c)
Checks if c is a Russian or an English letter.
void swap_ptrs (void **first, void **second)
Swaps contains of two ptrs.
void print_error (int error)
Prints text error message to standard output.
void get_next_letter (unsigned char **c)
int utest_compare_lines_letters ()
Variables
const int KCTF_DEBUG_LEVEL = 2
int DEBUG_NUMBER = 1
Just a mode for debugging.
unsigned char DEBUG_LETTER = 'a'
Just a char for debugging.
Detailed Description
General functions to be used in all projects.
Macro Definition Documentation
DEBUG
#define DEBUG(LEVEL) if (LEVEL <= KCTF_DEBUG_LEVEL)
Definition at line 22 of file general.h.
DEBUG_LETTER_INCR
#define DEBUG_LETTER_INCR() DEBUG_LETTER++;
Definition at line 20 of file general.h.
DEBUG_LETTER_PRINT
#define DEBUG_LETTER_PRINT() printf(`[deb] %c [deb]\n`, DEBUG_LETTER++);
Definition at line 17 of file general.h.
DEBUG_NUMBER_INCR
#define DEBUG_NUMBER_INCR() DEBUG_NUMBER++;
Definition at line 19 of file general.h.
DEBUG_NUMBER_PRINT
#define DEBUG_NUMBER_PRINT() printf(`[deb] %d [deb]\n`, DEBUG_NUMBER++);
Definition at line 16 of file general.h.
Typedef Documentation
File_t
typedef struct File File_t
Typedef for File.
Definition at line 14 of file general.h.
Line_t
typedef struct Line Line_t
Typedef for Line.
Definition at line 14 of file general.h.
Enumeration Type Documentation
CURRENT_PROJECT_SETTINGS
enum CURRENT_PROJECT_SETTINGS
Current project's setting.
Enumerator
STROFA_SIZE
RHYME_DEPTH
Definition at line 25 of file general.h.
                              { // special for Onegin
    STROFA_SIZE = 14,
    RHYME_DEPTH = 4
};
ERRORS
enum ERRORS
Errors codes.
Enumerator
ERROR_FILE_NOT_FOUND
ERROR_BIG_FILE
ERROR_MALLOC_FAIL
Definition at line 31 of file general.h.
            {
    ERROR_FILE_NOT_FOUND = -10,
    ERROR_BIG_FILE,
    ERROR_MALLOC_FAIL
};
Function Documentation
compare_lines_letters()
int compare_lines_letters (const void * elem1, const void * elem2)
Comparator for two lines.
Ignores everything that is not a Russian or English letter
Parameters
 in elem1,elem2 elements to compare
Returns
an int <0 if elem1<elem2, 0 if elem1=elem2, >0 if elem1>elem2
Definition at line 200 of file general.h.
                                                                {
    unsigned char *first_c = ((**(Line_t**)elem1).string);
    unsigned char *second_c = ((**(Line_t**)elem2).string);
    while (*first_c && *second_c) {
        get_next_letter(&first_c);
        get_next_letter(&second_c);
        if (*first_c != *second_c || (*first_c) * (*second_c) == 0) {
            return (int) *first_c - (int) *second_c;
        }
        ++first_c;
        ++second_c;
    }
    get_next_letter(&first_c);
    get_next_letter(&second_c);
    return (int) *first_c - (int) *second_c;
}
References get_next_letter().
Referenced by main(), reverse_compare_lines_letters(), and utest_compare_lines_letters().
free_memory_file()
void free_memory_file (const File_t * file)
Calls all necessary free's.
Kind of destructor for the File structure
Parameters
 in file object to be destroyed
Definition at line 224 of file general.h.
                                          {
    assert(file);
    Line_t **lines_ptr = file->lines;
    for (int i = 0; i < file->lines_cnt; ++i) {
        free(*lines_ptr);
        ++lines_ptr;
    }
    free(file->lines);
    free(file->text);
}
References File::lines, File::lines_cnt, and File::text.
Referenced by main().
get_next_letter()
void get_next_letter (unsigned char ** c)
Definition at line 192 of file general.h.
                                        {
    unsigned char *cur_c = *c;
    while(!is_countable(*cur_c) && *cur_c) {
        ++cur_c;
    }
    *c = cur_c;
}
References is_countable().
Referenced by compare_lines_letters().
is_countable()
int is_countable (const unsigned char c)
Checks if c is a Russian or an English letter.
Parameters
 in c char to check
Returns
true if c is a Russian or an English letter, else false
Definition at line 168 of file general.h.
                                        {
    return isalnum(c);
}
Referenced by calculate_ending(), get_next_letter(), and rhyme_compare_lines().
print_error()
void print_error (int error)
Prints text error message to standard output.
Parameters
 in error code of error to print
Definition at line 311 of file general.h.
                            {
    if (error == 0) {
        return;
    }
    if (error == ERROR_FILE_NOT_FOUND) {
        printf("[ERR] File not found!\n");
    } else if (error == ERROR_BIG_FILE) {
        printf("[ERR] Can't handle such a big file!\n");
    } else if (error == ERROR_MALLOC_FAIL) {
        printf("[ERR] Can't allocate memory\n");
    } else {
        printf("[ERR](~!~)WERRORHUTGEERRORF(~!~)[ERR]\n");
    }
}
References ERROR_BIG_FILE, ERROR_FILE_NOT_FOUND, and ERROR_MALLOC_FAIL.
Referenced by main().
print_file()
void print_file (const File_t * file, const char * fout_name, const char * mode)
Prints file into given file.
Parameters
 in file file containing text to write
 in output file name
Definition at line 299 of file general.h.
                                                                             {
    assert(file);
    assert(fout_name);
    FILE *fout = fopen(fout_name, mode);
    for (int i = 0; i < file->lines_cnt; ++i) {
        fprintf(fout, "%s\n", file->lines[i]->string);
    }
    fclose(fout);
}
References File::lines, File::lines_cnt, and Line::string.
Referenced by main().
qqh_sort()
void qqh_sort (void * arr, const size_t elem_cnt, const size_t elem_size, int(*)(const void *elem1, const void *elem2) comp)
Quadratic sort.
Sorts array on-place with given comparator
Parameters
 in arr array which needs to be sorted
 in elem_cnt count of elements, [0, elem_cnt) will be sorted
 in elem_size size of each element in bytes
 in comp comparator returning an int <0 of elem1<elem2, 0 if elem1=elem2, >0 if elem1>elem2
Definition at line 178 of file general.h.
                                                                                                                           {
    assert(arr);
    for (int i = 0; i < elem_cnt; ++i) {
        for (int j = 0; j < elem_cnt - 1; ++j) {
            void *first = arr + j * elem_size;
            void *second = arr + (j + 1) * elem_size;
            if (comp(first, second) > 0) {
                swap_ptrs(first, second);
            }
        }
    }
}
References swap_ptrs().
read_file()
int read_file (File_t * file, const char * name)
Reads file.
Estimates file's size and allocates just enough memory + 1 byte for \0, then calls read_lines to fill buffer 'text' and index 'lines'
Parameters
 in file object to be read to
 in name - filename to be read from
Returns
0 if file is read successfully, else error code <0
Definition at line 236 of file general.h.
                                              {
    assert(file);
    assert(name);
    file->name = name;
    stat(name, &(file->info));
    file->text = calloc(file->info.st_size + 1, sizeof(char));
    if (!file->text) {
        return ERROR_MALLOC_FAIL;
    }
    return file->lines_cnt = read_lines(file);
}
References ERROR_MALLOC_FAIL, File::info, File::lines_cnt, File::name, read_lines(), and File::text.
Referenced by main(), and utest_compare_lines_letters().
read_lines()
int read_lines (File_t * file)
Reads lines from file.
Stores them into given File_t object
Parameters
 in file an object to write into, contains input file name
Returns
0 if file is read successfully, else error code <0
Definition at line 250 of file general.h.
                             {
    assert(file);
    DEBUG(1) {printf("Working with [%s] file\n", file->name);}
    file->file_dscr = open(file->name, O_BINARY);
    read(file->file_dscr, file->text, file->info.st_size);
    int lines_cnt = 0;
    for (unsigned char *c = file->text; *c; ++c) {
        lines_cnt += *c == '\n';
    }
    file->lines = calloc(lines_cnt, sizeof(Line_t*));
    if (file->lines == NULL) {
        return ERROR_MALLOC_FAIL;
    }
    unsigned char *c = file->text;
    lines_cnt = -1;
    int line_len = 0;
    while (*c) {
        ++lines_cnt;
        file->lines[lines_cnt] = calloc(1, sizeof(Line_t));
        Line_t *line_ptr = file->lines[lines_cnt];
        if (line_ptr == NULL) {
            return ERROR_MALLOC_FAIL;
        }
        line_ptr->string = c;
        line_ptr->index = lines_cnt;
        while(*c != '\n') {
            ++line_len;
            ++c;
            if (*c == '\r') {
                *c = '\0';
            }
        }
        *c = '\0';
        ++c;
        line_ptr->len = line_len;
        line_len = 0;
    }
    file->lines_cnt = lines_cnt + 1;
    return lines_cnt + 1;
}
References DEBUG, ERROR_MALLOC_FAIL, File::file_dscr, Line::index, File::info, Line::len, File::lines, File::lines_cnt, File::name, Line::string, and File::text.
Referenced by read_file().
reverse_compare_lines_letters()
int reverse_compare_lines_letters (const void ** elem1, const void ** elem2)
Reversed comparator for two lines.
Ignores everything that is not a Russian or English letter
Parameters
 in elem1,elem2 elements to compare
Returns
an int >0 if elem1<elem2, 0 if elem1=elem2, 0 if elem1>elem2
Definition at line 220 of file general.h.
                                                                          {
    return -compare_lines_letters(elem1, elem2);
}
References compare_lines_letters().
swap_ptrs()
void swap_ptrs (void ** first, void ** second)
Swaps contains of two ptrs.
Parameters
 in first,second prts to swap
Returns
Definition at line 172 of file general.h.
                                            {
    void *tmp = *second;
    *second = *first;
    *first = tmp;
}
Referenced by qqh_sort().
utest_compare_lines_letters()
int utest_compare_lines_letters ()
Definition at line 330 of file general.h.
                                  {
    srand(time(NULL));
    File_t file = {};
    read_file(&file, "utest_compare_lines_letters.txt");
    for (size_t itter = 0; itter < 1000; ++itter) {
        for (size_t i = 0; i < file.lines_cnt / 2; ++i) {
            const size_t x = rand() % file.lines_cnt;
            const size_t y = rand() % file.lines_cnt;
            Line_t *tmp = file.lines[x];
            file.lines[x] = file.lines[y];
            file.lines[y] = tmp;
        }
        qsort(file.lines, file.lines_cnt, sizeof(Line_t*), compare_lines_letters);
        for (int i = 0; i < file.lines_cnt - 1; ++i) {
            if (file.lines[i]->index > file.lines[i + 1]->index && compare_lines_letters(&file.lines[i], &file.lines[i + 1])) {
                printf("[ERR] \"%s\" > \"%s\"\n", file.lines[i]->string, file.lines[i + 1]->string);
                printf("[ ! ] indexes: %d > %d\n", file.lines[i]->index, file.lines[i + 1]->index);
                DEBUG(2) {
                    printf("====\n");
                    for (int i = 0; i < file.lines_cnt; ++i) {
                        printf("%s\n", file.lines[i]->string);
                    }
                }
            }
        }
    }
    return 0;
}
References compare_lines_letters(), DEBUG, Line::index, File::lines, File::lines_cnt, read_file(), and Line::string.
Referenced by main().
Variable Documentation
DEBUG_LETTER
unsigned char DEBUG_LETTER = 'a'
Just a char for debugging.
Definition at line 14 of file general.h.
DEBUG_NUMBER
int DEBUG_NUMBER = 1
Just a mode for debugging.
Just an int for debugging
Definition at line 13 of file general.h.
KCTF_DEBUG_LEVEL
const int KCTF_DEBUG_LEVEL = 2
Definition at line 11 of file general.h.