C:/Users/maxim/Desktop/mipt/grade_1/course_dedinskiy/hw_onegin/onegin.h File Reference
Main library for Onegin to work.
#include <assert.h>
#include `general.h`
Functions
void calculate_ending (Line_t *line, const size_t rhyme_depth)
Calculates an ending of a line.
int rhyme_compare_lines (const void **elem1, const void **elem2)
End-starting comparator for two lines.
char rhyming_lines (const Line_t *first, const Line_t *second, const size_t depth)
Checks if lines are rhyming.
void gen_strofa (const Line_t **lines, const size_t lines_cnt, unsigned int *buffer, const size_t rhyme_depth)
Generates new strofa from random strings.
Detailed Description
Main library for Onegin to work.
Function Documentation
calculate_ending()
void calculate_ending (Line_t * line, const size_t rhyme_depth)
Calculates an ending of a line.
Ignores all symbols that are not letters in the end of string takes last RHYME_DEPTH chars Stores output into given line. Works for rhyming purposes
Parameters
 in line line to be process
Definition at line 59 of file onegin.h.
                                                              {
    int i = line->len - 1;
    while(!is_countable(line->string[i]) && i) {
        --i;
    }
    if (!i) {
        return;
    }
    for (int j = 0; j < rhyme_depth; ++j) {
        line->ending[j] = line->string[i - rhyme_depth + j + 1];
    }
}
References Line::ending, is_countable(), Line::len, and Line::string.
Referenced by main().
gen_strofa()
void gen_strofa (const Line_t ** lines, const size_t lines_cnt, unsigned int * buffer, const size_t rhyme_depth)
Generates new strofa from random strings.
Given NOT MESSED UP lines of Onegin generates indexes of strings to be used in new strofa
Parameters
 in lines stringview over text of Onegin
 in lines_cnt number of lines in text
 out buffer array of size_t to store output into
 in RHYME_DEPTH depth of rhyme to check (look at rhyming_lines for desription)
Definition at line 110 of file onegin.h.
                                                                                                              {
    assert(lines);
    assert(buffer);
    srand(time(NULL));
    for (int i = 0; i < STROFA_SIZE; ++i) {
        int itter = 0;
        while (1) {
            ++itter;
            if (itter == 100) {
                i = 0;
                continue;
            }
            int line_index = (((int) rand()) % (lines_cnt / 14)) * 14 + i;
            const Line_t *line = lines[line_index];
            if (i == 0 || i == 1 || i == 4 || i == 6 || i == 8 || i == 9 || i == 12) { // COMMENTS
                buffer[i] = line_index;
                break;
            } else if (i == 5 || i == 7 || i == 10 || i == 13) {
                if (rhyming_lines(line, lines[buffer[i - 1]], rhyme_depth)) {
                    buffer[i] = line_index;
                    break;
                }
            } else if (i == 2 || i == 3) {
                if (rhyming_lines(line, lines[buffer[i - 2]], rhyme_depth)) {
                    buffer[i] = line_index;
                    break;
                }
            } else {
                if (rhyming_lines(line, lines[buffer[i - 3]], rhyme_depth)) {
                    buffer[i] = line_index;
                    break;
                }
            }
        }
    }
}
References File::lines, File::lines_cnt, rhyming_lines(), and STROFA_SIZE.
Referenced by main().
rhyme_compare_lines()
int rhyme_compare_lines (const void ** elem1, const void ** elem2)
End-starting comparator for two lines.
Compares two lines representing them as reversed without manually doing this
Parameters
 in elem1,elem2 lines to compare
Returns
an int <0 if elem1<elem2, 0 if elem1=elem2, >0 if elem1>elem2
Definition at line 73 of file onegin.h.
                                                                {
    const Line_t *line1 = *elem1;
    const Line_t *line2 = *elem2;
    const unsigned char* str1 = line1->string;
    const unsigned char* str2 = line2->string;
    int i = line1->len - 1;
    int j = line2->len - 1;
    while (i >= 0 && j >= 0) {
        while (!is_countable(str1[i]) && str1[i]) {
            --i;
        }
        while (!is_countable(str2[j]) && str2[j]) {
            --j;
        }
        if (str1[i] != str2[j] || i * j == 0) {
            return str1[i] - str2[j];
        }
        --i;
        --j;
    }
    return str1[i] - str2[j];
}
References is_countable(), Line::len, and Line::string.
rhyming_lines()
char rhyming_lines (const Line_t * first, const Line_t * second, const size_t depth)
Checks if lines are rhyming.
Compares endings of the lines that are calculated by calculate_ending function rhyming strings are those having RHYME_DEPTH-1 symbols same in the end and difference in RHYME_DEPTH symbol from the end
Parameters
 in first,second given string to check rhyming
Returns
true if lines are rhyming, else false
Definition at line 99 of file onegin.h.
                                                                                  {
    if (first == second) {
        return 0;
    }
    if (strcmp((char*) first->ending + 1, (char*) second->ending + 1) || first->ending[0] == second->ending[0]) {
        return 0;
    }
    return 1;
}
References Line::ending.
Referenced by gen_strofa().